### ISSUE TITLE
Outputs empty list of jobs

### ISSUE THREAD

**Issue by turion** [Kleidukos/get-tested#10]
I tried to use `get-tested` here: https://github.com/turion/rhine/pull/201

But unfortunately, the list of versions is always empty. I reproduced locally:

```
$ ./get-tested --ubuntu --macos rhine/rhine.cabal 
matrix={"include":[]}
```

The corresponding section is:

```
tested-with:
  GHC == 8.8.4,
  GHC == 8.10.7,
  GHC == 9.0.2
```

**Comment by turion** [comment]
After cloning your repo and debugging, this seems to be an upstream issue with cabal.

**Comment by turion** [comment]
Ah, this was tricky. I had a `source-repository` section which silently swallowed the tested-with stanza.

**Comment by Kleidukos** [comment]
Got it!
