### ISSUE TITLE
Add support for selecting the runner version

### ISSUE THREAD

**Issue by DavidMazarro** [Kleidukos/get-tested#32]
Hi! Nice to meet you! First of all thanks for creating this tool and GH Action ❤️

I'm trying to push for the adoption of this GH Action at @stackbuilders for some of the repos we maintain. I was having a slightly unrelated conversation with regards to the macOS runners that GitHub offers, and wanted to test the `macos-14` one since that uses Apple Silicon (`macos-latest` is based on `macos-12` which is currently x86-64 based AFAIK). But I noticed that this tool doesn't currently support that, and that it has the `*-latest` versions hardcoded.

I think it would be nice to support choosing the runner version for each OS. Adding a new input to the action that allows one to set an explicit list of the OS runners one wants to support could be a possible approach.

I am willing to try to work on this, unless you prefer doing that. Let me know if you have any ideas/preferences with regards to how you would like to see this reflected in the action.

**Comment by Kleidukos** [comment]
@DavidMazarro hi David, glad to hear this is action is getting traction! I will create a PR for this. Do you mind if I ask a review from you once it's ready?

**Comment by DavidMazarro** [comment]
@Kleidukos By all means! Thanks for taking a look at this ^^

**Comment by Kleidukos** [comment]
@DavidMazarro Turns out it was simpler than expected. Would you mind trying out v0.1.7.0? The instructions are in the README.

**Comment by DavidMazarro** [comment]
It works! Feel free to close this issue. I might have other ideas for potential ways to make the tool/GH Action more expressive in terms of runner/GHC version possible configurations, but I'll create issues for those (before that, I'll consider if they are feasible without going against the philosophy of the tool).

Thank you so much!
