### ISSUE TITLE
Only take precise versions and reject version ranges

### ISSUE THREAD

**Issue by Kleidukos** [Kleidukos/get-tested#7]
We should encourage people to use the exact-version syntax, and not use version ranges. For instance

```
tested-with: GHC == { 8.6.3, 8.4.4, 8.2.2, 8.0.2, 7.10.3, 7.8.4, 7.6.3, 7.4.2 }
```

or

```
tested-with: GHC == 8.6.3, GHC == 8.4.4, GHC == 8.2.2, GHC == 8.0.2,
             GHC == 7.10.3, GHC == 7.8.4, GHC == 7.6.3, GHC == 7.4.2
```

This frees us from having to maintain a whitelist.

**Comment by andreasabel** [comment]
Or the diff-friendly line-wise syntax maybe, which I prefer:
```
tested-with: 
  GHC == 8.6.3
  GHC == 8.4.4
  GHC == 8.2.2
  GHC == 8.0.2
  GHC == 7.10.3
  GHC == 7.8.4
  GHC == 7.6.3
  GHC == 7.4.2
```

**Comment by Kleidukos** [comment]
Yes, in the end it's the version ranges that we should avoid, they're absolutely tricky to validate without maintaining a whitelist.
