### ISSUE TITLE
mleh! (Outputs unhelpful error message)

### ISSUE THREAD

**Issue by turion** [Kleidukos/get-tested#9]
I mistyped the name of the cabal file in my CI setup, and I got this error message:

```
get-tested: mleh!
CallStack (from HasCallStack):
  error, called at app/Main.hs:28:15 in main:Main
Error: Process completed with exit code 1.
```

This is fun, but not helpful ;) a better error message would have been something like `mleh! File foo.cabal could not be found!`

**Comment by Kleidukos** [comment]
yep :)
